GET http://127.0.0.1:8000/hello/2021







###
POST http://127.0.0.1:8082/users/
Content-Type: application/json

{
    "name": "joao",
    "email": "joao@email.com",
    "password": "12345"
}

###
POST http://127.0.0.1:8082/users/2/measures/
Content-Type: application/json

{
    "height": 170,
    "weight": 50,
    "thighs": 4,
    "calf": 4,
    "id": 1,
}


###
GET http://127.0.0.1:8082/users/1/measures/


###
GET http://127.0.0.1:8082/measures/




###
GET http://127.0.0.1:8082/users/







###
GET http://127.0.0.1:8082/users/1


###
GET http://127.0.0.1:8082/users/2

###
PUT http://127.0.0.1:8082/users/1
Content-Type: application/json

{
    
}









###
POST http://127.0.0.1:8000/users
Content-Type: application/json

{
    "name": "Ricardo Silva",
    "email": "ricardo.silva@email.com"
}








###
PUT http://127.0.0.1:8000/users/8
Content-Type: application/json

{
    "name": "Nome",
    "price": 1
}

### 
DELETE http://127.0.0.1:8000/users/8
